In [38]:
import pandas as pd

In [39]:
fruit_names=pd.Series(["Apple","Banana","Cherry"])
fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [40]:
pd.Series(["Apple","Banana","Cherry"],dtype='string')

0     Apple
1    Banana
2    Cherry
dtype: string

In [41]:
pd.Series(["Apple","Banana","Cherry"],dtype=pd.StringDtype)

C:\Users\KDS13\AppData\Local\Temp\ipykernel_13548\4246623600.py:1: UserWarning: Instantiating StringDtype without any arguments.Pass a StringDtype instance to silence this warning.
  pd.Series(["Apple","Banana","Cherry"],dtype=pd.StringDtype)

0     Apple
1    Banana
2    Cherry
dtype: string

In [42]:
fruit_names.astype("string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [43]:
#문자열 메소드
import pandas as pd
import numpy as np

ser=pd.Series(['Apple_사과','Banana_바나나','Cherry_체리',np.nan],index=["First "," Second"," Third", "Fourth"])
ser2=pd.Series(['Apple_사과','Banana_바나나','Cherry_체리',np.nan],index=["First "," Second"," Third", "Fourth"],dtype='string')
print(ser)
print(ser2)

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: str
First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth           <NA>
dtype: string

In [44]:
#소문자로 변환
print(ser.str.lower())
print("\n")
#대문자로 변환
print(ser.str.upper())
print("\n")
#문자열 길이 계산
print(ser.str.len())

First        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Fourth            NaN
dtype: str


First        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Fourth            NaN
dtype: str


First       8.0
 Second    10.0
 Third      9.0
Fourth      NaN
dtype: float64

In [45]:
#문자열 분할
print(ser.str.split("_"))
print("\n")
#문자열을 분할하여 데이터프레임으로 확장
print(ser.str.split("_",expand=True))
print("\n")
#분할된 문자열 중 특정 요소 선택
print(ser.str.split("_").str.get(1))

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Fourth               NaN
dtype: object


              0    1
First     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Fourth      NaN  NaN


First       사과
 Second    바나나
 Third      체리
Fourth     NaN
dtype: object

In [46]:
#문자열 메소드
#행 인덱스 추출
idx=ser.index
print(idx)
print("\n")
#양쪽 공백 제거
print(idx.str.strip())

Index(['First ', ' Second', ' Third', 'Fourth'], dtype='str')


Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')

In [47]:
#문자열 교체
print(ser.str.replace("_",":",regex=False))
print("\n")

#정규 표현식을 사용한 문자열 교체
print(ser.str.replace("[^a-zA-Z\s]","",regex=True))

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Fourth            NaN
dtype: str


First       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: str

<>:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\KDS13\AppData\Local\Temp\ipykernel_13548\185340319.py:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  print(ser.str.replace("[^a-zA-Z\s]","",regex=True))

In [48]:
#인덱싱-각 문자열의 첫 번째 문자 선택
print(ser.str[0])

First        A
 Second      B
 Third       C
Fourth     NaN
dtype: str

In [49]:
#슬라이싱- 각 문자열의 첫 번째부터 세 번째 문자 선택
print(ser.str[0:4])

First      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: str

In [50]:
#특정 문자 포함 여부 확인, NA값을 False로 처리
contains_A=ser.str.contains("A",na=False)
print(contains_A)

First       True
 Second    False
 Third     False
Fourth     False
dtype: bool

In [51]:
#패턴 포함 여부 확인
contains_pattern=ser.str.contains(r"[A|B][a-z]+")
print(contains_pattern)

First       True
 Second     True
 Third     False
Fourth     False
dtype: bool

In [52]:
#전체 문자열의 패턴 일치 여부 확인
fullmatch_pattern=ser.str.fullmatch(r"[A|B][a-z]+")
print(fullmatch_pattern)

First      False
 Second    False
 Third     False
Fourth     False
dtype: bool

In [53]:
#새로운 시리즈 생성
ser3=pd.Series(['a1','b2','c3','d4a5','e6e7','f8'],dtype='string')

#숫자만 추출
digits=ser3.str.extractall(r"(\d)").groupby(level=0).agg(''.join)
print(digits)

    0
0   1
1   2
2   3
3  45
4  67
5   8

In [54]:
#알파벳만 추출
letters=ser3.str.extractall(r"([a-z])").groupby(level=0).agg(''.join)
letters

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [56]:
#숫자를 별도의 칼럼으로 분리
split_columns=ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")
split_columns

  Letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8