In [8]:
# 라이브러리 불러오기
import pandas as pd

# 판다스 DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장 
data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   #name 열을 인덱스로 지정

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [9]:
# to_csv() 메소드를 사용하여 CSV 파일로 내보내기. 파열명은 df_sample.csv로 저장
df.to_csv("../data/df_sample.csv")

In [11]:
# index = False
df.to_csv("../data/df_sample_no_index.csv", index = False)

In [ ]:
##JSON 파일로 저장

In [12]:
# 라이브러리 불러오기
import pandas as pd

# 판다스 DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장 
data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   #name 열을 인덱스로 지정

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [14]:
# to_json() 메소드를 사용하여 JSON 파일로 내보내기. 파열명은 df_sample.json로 저장
df.to_json("../data/df_sample.json")

In [ ]:
# orient='split'
df.to_json("../data/df_sample_split.json", orient='split')

In [19]:
# orient='records'
df.to_json("../data/df_sample_records.json", orient='records')

In [21]:
# orient='index'
df.to_json("../data/df_sample_index.json", orient='index')

In [22]:
# orient='columns'
df.to_json("../data/df_sample_columns.json", orient='columns')

In [24]:
# orient='values'
df.to_json("../data/df_sample_values.json", orient='values')

In [25]:
#Excel파일로 저장

In [26]:
import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   #name 열을 인덱스로 지정

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [28]:
df=pd.DataFrame(data)
df=df.set_index('name')
df
# to_excel() 메소드를 사용하여 엑셀 파일로 내보내기. 파열명은 df_sample.xlsx로 저장
df.to_excel("../data/df_sample.xlsx")

In [30]:
# index = False
df.to_excel("../data/df_sample_no_index.xlsx", index = False)

In [31]:
#여러 개의 데이터프레임을 하나의 Excel파일로 저장
import pandas as pd

data1 = {'name' : [ 'Jerry', 'Riah', 'Paul'],
         'algol' : [ "A", "A+", "B"],
         'basic' : [ "C", "B", "B+"],
          'c++' : [ "B+", "C", "C+"]}

data2 = {'c0':[1,2,3], 
         'c1':[4,5,6], 
         'c2':[7,8,9], 
         'c3':[10,11,12], 
         'c4':[13,14,15]}

df1 = pd.DataFrame(data1)
df1 = df1.set_index('name')      #name 열을 인덱스로 지정
print(df1)
print('\n')

df2 = pd.DataFrame(data2)
df2 = df2.set_index('c0')        #c0 열을 인덱스로 지정
print(df2)

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+


    c1  c2  c3  c4
c0
1    4   7  10  13
2    5   8  11  14
3    6   9  12  15

In [ ]:
#df1을 'sheet1'으로, df2를 'sheet2'로 저장 (하나의 파일에 두개의 시트)
with pd.ExcelWriter("../data/df_excelwriter.xlsx") as writer:
    df1.to_excel(writer, sheet_name="sheet1")
    df2.to_excel(writer, sheet_name="sheet2")